In [5]:
import numpy as np
import matplotlib.pyplot as plt

def demostracion_grafica_p2_mejorada(n_muestras=200):
    """
    Realiza una demostración mejorada para p=2, calculando explícitamente los
    autovectores de T_g1 y usando un gráfico más intuitivo.
    """
    p = 2
    print("=" * 60)
    print(f"DEMOSTRACIÓN GRÁFICA MEJORADA PARA p={p}")
    print("=" * 60)

    # --- PASO 1 y 2: Generar datos y calcular S (sin cambios) ---
    print("\n--- PASO 1 & 2: Generando datos y calculando S ---")
    sigma_true = np.array([[3, 2.8], [2.8, 3]]) 
    media = np.array([0, 0])
    datos = np.random.multivariate_normal(mean=media, cov=sigma_true, size=n_muestras)
    S = np.cov(datos, rowvar=False)
    print("Matriz S calculada:")
    print(np.round(S, 4))

    # --- PASO 3: Descomposición espectral de S ---
    print("\n--- PASO 3: Descomposición espectral de S ---")
    lambdas_S, U_S = np.linalg.eigh(S)
    v1_S = U_S[:, 0]
    v2_S = U_S[:, 1]
    print(f"Autovalores de S: {np.round(lambdas_S, 4)}")
    print(f"Autovectores de S (columnas de U_S):\n{np.round(U_S, 4)}")

    # --- PASO 4: Calcular el estimador objetivo T_g1 ---
    print("\n--- PASO 4: Calculando T_g1 ---")
    varianzas = np.diag(S)
    c = np.prod(varianzas)**(1/p)
    Tg1 = c * np.identity(p)
    print(f"Escalar 'c': {c:.4f}")
    print(f"Matriz T_g1 (c * I):\n{np.round(Tg1, 4)}")

    # --- PASO 4.5: ¡NUEVO! Descomposición espectral de T_g1 ---
    print("\n--- PASO 4.5: Descomposición espectral de T_g1 (explícita) ---")
    lambdas_Tg1, U_Tg1 = np.linalg.eigh(Tg1)
    print(f"Autovalores de T_g1: {np.round(lambdas_Tg1, 4)}")
    print(f"Autovectores de T_g1 (calculados por el algoritmo):\n{np.round(U_Tg1, 4)}")
    print("\nAnálisis Importante:")
    print(f"  - Como se esperaba, ambos autovalores de T_g1 son iguales a 'c' ({c:.4f}).")
    print( "  - Debido a esta 'degeneración' (autovalores idénticos), CUALQUIER vector en el plano es un autovector.")
    print( "  - Por lo tanto, el conjunto de autovectores de S es un subconjunto válido de los autovectores de T_g1.")


    # --- PASO 5: Verificación (sin cambios) ---
    print("\n--- PASO 5: Verificando que los autovectores de S son autovectores de T_g1 ---")
    es_autovector1 = np.allclose(Tg1 @ v1_S, c * v1_S)
    es_autovector2 = np.allclose(Tg1 @ v2_S, c * v2_S)
    print(f"¿Es v1_S un autovector de T_g1? -> {es_autovector1}")
    print(f"¿Es v2_S un autovector de T_g1? -> {es_autovector2}")

    # --- PASO 6: ¡NUEVO! Visualización mejorada ---
    print("\n--- PASO 6: Generando el gráfico mejorado ---")
    
    plt.figure(figsize=(10, 10))
    origen = [0, 0]
    
    # Dibujar la nube de puntos
    plt.scatter(datos[:, 0], datos[:, 1], alpha=0.2, label='Datos generados', zorder=1)
    
    # 1. Dibujar el primer autovector de S (v1_S) como referencia
    plt.quiver(*origen, *v1_S, color='k', scale=1, scale_units='xy', angles='xy',
               label='Autovector de S (v1_S)', zorder=2)
    
    # 2. Mostrar el resultado de transformar v1_S con T_g1
    v1_S_transformado = Tg1 @ v1_S
    plt.quiver(*origen, *v1_S_transformado, color='r', linestyle='--', scale=1, scale_units='xy', angles='xy',
               label=f'T_g1 @ v1_S (escalado por c={c:.2f})', zorder=3)
    
    # Repetir para el segundo autovector (v2_S)
    plt.quiver(*origen, *v2_S, color='k', scale=1, scale_units='xy', angles='xy',
               label='Autovector de S (v2_S)', zorder=2)
    v2_S_transformado = Tg1 @ v2_S
    plt.quiver(*origen, *v2_S_transformado, color='b', linestyle='--', scale=1, scale_units='xy', angles='xy',
               label=f'T_g1 @ v2_S (escalado por c={c:.2f})', zorder=3)
    
    # Configuraciones del gráfico
    plt.title("Demostración: T_g1 transforma los autovectores de S sin cambiar su dirección", fontsize=14)
    plt.xlabel("Variable 1")
    plt.ylabel("Variable 2")
    plt.axhline(0, color='grey', lw=0.5)
    plt.axvline(0, color='grey', lw=0.5)
    plt.grid(True, linestyle=':', alpha=0.7)
    
    # Unificar leyendas para no repetir etiquetas
    handles, labels = plt.gca().get_legend_handles_labels()
    by_label = dict(zip(labels, handles))
    plt.legend(by_label.values(), by_label.keys(), fontsize=11)
    
    plt.axis('equal')
    plt.show()


# --- Ejecutar la demostración ---
if __name__ == "__main__":
    demostracion_grafica_p2_mejorada()

DEMOSTRACIÓN GRÁFICA MEJORADA PARA p=2

--- PASO 1 & 2: Generando datos y calculando S ---
Matriz S calculada:
[[3.0367 2.897 ]
 [2.897  3.191 ]]

--- PASO 3: Descomposición espectral de S ---
Autovalores de S: [0.2158 6.0119]
Autovectores de S (columnas de U_S):
[[-0.7165  0.6976]
 [ 0.6976  0.7165]]

--- PASO 4: Calculando T_g1 ---
Escalar 'c': 3.1129
Matriz T_g1 (c * I):
[[3.1129 0.    ]
 [0.     3.1129]]

--- PASO 4.5: Descomposición espectral de T_g1 (explícita) ---
Autovalores de T_g1: [3.1129 3.1129]
Autovectores de T_g1 (calculados por el algoritmo):
[[1. 0.]
 [0. 1.]]

Análisis Importante:
  - Como se esperaba, ambos autovalores de T_g1 son iguales a 'c' (3.1129).
  - Debido a esta 'degeneración' (autovalores idénticos), CUALQUIER vector en el plano es un autovector.
  - Por lo tanto, el conjunto de autovectores de S es un subconjunto válido de los autovectores de T_g1.

--- PASO 5: Verificando que los autovectores de S son autovectores de T_g1 ---
¿Es v1_S un autovector de T_

ValueError: At least one value in the dash list must be positive

<Figure size 1000x1000 with 1 Axes>

In [12]:
import numpy as np
from scipy.linalg import logm

def demo_impostor_vs_real(p=3):
    """
    Demuestra que una descomposición 'falsa' V*W*V^T no se puede usar
    para calcular funciones de la matriz A.
    """
    print("=" * 80)
    print("DEMOSTRACIÓN: DESCOMPOSICIÓN 'FALSA' vs. 'REAL' PARA FUNCIONES DE MATRICES")
    print("=" * 80)

    # --- PASO 1: Construcción 'Falsa' con V y W ---
    print("\n--- PASO 1: Construyendo A = V * W * V^T ---")
    
    # Crear una matriz ortogonal aleatoria V
    V, _ = np.linalg.qr(np.random.rand(p, p))
    print("Matriz ortogonal 'V' creada.")

    # Crear una matriz W simétrica, NO-DIAGONAL y con autovalores positivos
    # para que su logaritmo esté definido.
    M = np.random.rand(p, p)
    W = M.T @ M + np.identity(p) # Garantiza que sea simétrica y definida positiva
    print("\nMatriz simétrica 'W' (no diagonal) creada:")
    print(np.round(W, 4))
    
    # Construir la matriz A. Como W y V son reales, A será simétrica.
    A = V @ W @ V.T
    print("\nMatriz A final construida:")
    print(np.round(A, 4))


    # --- PASO 2: Descomposición Espectral 'Verdadera' de A ---
    print("\n--- PASO 2: Encontrando la descomposición espectral real A = U * B * U^T ---")
    
    autovalores_B, U = np.linalg.eigh(A)
    B = np.diag(autovalores_B)
    
    print("Matriz de autovectores 'U' (diferente a V):")
    print(np.round(U, 4))
    print("\nMatriz diagonal de autovalores 'B' (diferente a W):")
    print(np.round(B, 4))
    

    # --- PASO 3: Calcular ambos lados de la ecuación de comparación ---
    print("\n--- PASO 3: Comparando V*log(W)*V^T  vs  U*log(B)*U^T ---")
    
    # Lado Izquierdo (LHS): Usando la construcción 'falsa'
    # Necesitamos el logaritmo de la matriz W, no el logaritmo de sus elementos.
    log_W = logm(W)
    LHS = V @ log_W @ V.T
    print("\nLado Izquierdo (LHS) = V * log(W) * V^T:")
    print(np.round(LHS, 4))

    # Lado Derecho (RHS): Usando la descomposición 'verdadera'
    # Como B es diagonal, su logaritmo es el logaritmo de sus elementos diagonales.
    log_B = np.diag(np.log(autovalores_B))
    RHS = U @ log_B @ U.T
    print("\nLado Derecho (RHS) = U * log(B) * U^T  (esta es la definición de log(A))")
    print(np.round(RHS, 4))


    # --- PASO 4: Conclusión y Verificación ---
    print("\n" + "=" * 80)
    print("CONCLUSIÓN")
    print("=" * 80)
    
    # La comparación final
    son_iguales = np.allclose(LHS, RHS)
    print(f"¿Son V*log(W)*V^T  y  U*log(B)*U^T iguales? \t-> {son_iguales}")
    
    # Verificación adicional: calculemos log(A) directamente
    log_A_real = logm(A)
    print("\nVerificación con el cálculo directo de log(A):")
    print(f"¿Es el RHS igual a log(A)? \t\t\t-> {np.allclose(RHS, log_A_real)}")
    print(f"¿Es el LHS igual a log(A)? \t\t\t-> {np.allclose(LHS, log_A_real)}")


# --- Ejecutar la demostración ---
if __name__ == "__main__":
    demo_impostor_vs_real()

DEMOSTRACIÓN: DESCOMPOSICIÓN 'FALSA' vs. 'REAL' PARA FUNCIONES DE MATRICES

--- PASO 1: Construyendo A = V * W * V^T ---
Matriz ortogonal 'V' creada.

Matriz simétrica 'W' (no diagonal) creada:
[[1.5015 0.1411 0.3988]
 [0.1411 1.8362 1.0154]
 [0.3988 1.0154 2.5189]]

Matriz A final construida:
[[ 1.4183 -0.1396  0.1546]
 [-0.1396  3.2461 -0.4087]
 [ 0.1546 -0.4087  1.1922]]

--- PASO 2: Encontrando la descomposición espectral real A = U * B * U^T ---
Matriz de autovectores 'U' (diferente a V):
[[ 0.3474  0.9337 -0.0865]
 [-0.1513  0.1469  0.9775]
 [-0.9254  0.3265 -0.1923]]

Matriz diagonal de autovalores 'B' (diferente a W):
[[1.0673 0.     0.    ]
 [0.     1.4504 0.    ]
 [0.     0.     3.3389]]

--- PASO 3: Comparando V*log(W)*V^T  vs  U*log(B)*U^T ---

Lado Izquierdo (LHS) = V * log(W) * V^T:
[[ 0.3411 -0.0544  0.1125]
 [-0.0544  1.1615 -0.1997]
 [ 0.1125 -0.1997  0.14  ]]

Lado Derecho (RHS) = U * log(B) * U^T  (esta es la definición de log(A))
[[ 0.3411 -0.0544  0.1125]
 [-0.0544